name: pubnub-angular
version: 4.2.0
schema: 1
scm: github.com/pubnub/pubnub-angular
changelog:
  - version: v4.2.0
    date: 2019-05-24
    changes:
      - type: feature
        text: Add reconnect for v4 wrapper
      - type: fix
        text: Fix for encrypt method with customCipherKey
  - version: v4.1.0
    date: 2017-10-30
    changes:
      - type: feature
        text: Add deleteMessages and fetchMessages for v4 wrapper
      - type: fix
        text: Active events broadcaster only with the param triggerEvent
  - version: v4.0.3
    date: 2017-09-21
    changes:
      - type: feature
        text: Add delegated method setHeartbeatInterval for v4 wrapper
  - version: v4.0.2
    date: 2016-11-14
    changes:
      - type: fix
        text: Add delegated method setFilterExpression for v4 wrapper
  - version: v4.0.1
    date: 2016-11-11
    changes:
      - type: fix
        text: Add missing delegated methods (v3 -> fire, v4 -> removeListener, push, unsubscribeAll, decrypt, encrypt, fire )
  - version: v4.0.0
    date: 2016-10-06
    changes:
      - type: feature
        text: V4 support.
  - version: v3.2.1
    date: 2016-06-13
    changes:
      - type: improvement
        text: |
          When subscribing directly to a -pnpres channel, the AngularJS events were broadcasted on the channel itself and not on the -pnpres channel as it should have been.
      - type: improvement
        text: |
          $pubnubChannel.$extend(): Avoid to share extensions across every $pubnubChannel objects.
  - version: v3.2.0
    date: 2016-05-10
    changes:
      - type: feature
        text: Adding new $pubnubChannel and $pubnubChannelGroup injectables to simplify working with channel and channel groups
  - version: v3.1.2
    date: 2016-05-02
    changes:
      - type: improvement
        text: Adjustments to build package and upgraded dependencies.
  - version: v3.1.1
    date: 2016-01-27
    changes:
      - type: feature
        text: |
          [#18](https://github.com/pubnub/pubnub-angular/pull/18) adding `mobile_gw_provision` to the delegated methods ([@kminkler](https://github.com/kminkler))
  - version: 3.1.0
    date:
    changes:
      - type: improvement
        text: added eslint, babel and webpack to the compilation process
  - version: 3.0.0
    date:
    changes:
      - type: feature
        text: |
          full rewrite :)
